"""Paired ON/OFF ablation harness for /v1/cua quality toggles.

Usage:
    export MANTIS_ENDPOINT=https://getmason--mantis-server-api.modal.run
    export MANTIS_API_TOKEN=mantis_...
    python scripts/ablate_v1_cua.py \\
        --toggle perceptual_verify \\
        --instruction "Find a sign-in button and click it. Then call done." \\
        --start-url https://lu.ma/discover \\
        --pairs 2

What it does:
    1. Warm-up request (results discarded) so subsequent requests reuse
       the Chrome session cache and don't include ~10s cold-start noise.
    2. For each pair: one request with the toggle OFF, one with the
       toggle ON, against the same warm container. Identical instruction
       across both arms.
    3. Parses /v1/cua response aggregates and prints a side-by-side diff
       so PR authors can decide "no regression" with evidence.

Discipline (per project memory):
    Any PR touching the runner / brain / verification surfaces must
    include an Ablation report in the PR body, generated by this script.
    Speedup-only changes can use Run #1 only; quality changes need at
    least 2 pairs to catch noisy regressions.

Available toggles (per-request override surface added to /v1/cua):
    perceptual_verify (#293)   loop_recovery (#302)   done_gate (#303)
    predicate_verify (#291)    adaptive_settle (#294)  form_controller (#301)
    reuse_session (#311)       speculation (#118)     loop_adaptive (#298)
    adaptive_click_tol (#296)
"""

from __future__ import annotations

import argparse
import json
import os
import statistics
import sys
import time
from typing import Any

import requests


_AGGREGATE_FIELDS: tuple[str, ...] = (
    "success",
    "steps",
    "termination_reason",
    "elapsed_seconds",
    "reused_session",
    "predicate_summary",
    "perceptual_summary",
    "loop_recoveries_by_reason",
    "done_rejections_by_reason",
    "speculation_summary",
)


def _post_cua(
    endpoint: str,
    token: str,
    *,
    instruction: str,
    start_url: str,
    max_steps: int,
    settle_time: float,
    proxy_disabled: bool,
    toggle: str | None,
    toggle_value: bool | None,
    timeout: float,
) -> dict[str, Any]:
    body: dict[str, Any] = {
        "instruction": instruction,
        "start_url": start_url,
        "max_steps": max_steps,
        "settle_time": settle_time,
        "proxy_disabled": proxy_disabled,
    }
    if toggle is not None and toggle_value is not None:
        body[toggle] = toggle_value

    started = time.monotonic()
    resp = requests.post(
        f"{endpoint.rstrip('/')}/v1/cua",
        json=body,
        headers={
            "X-Mantis-Token": token,
            "Content-Type": "application/json",
        },
        timeout=timeout,
        allow_redirects=True,
    )
    wall = time.monotonic() - started
    if resp.status_code >= 400:
        return {
            "_error": f"http={resp.status_code}",
            "_body_head": resp.text[:200],
            "_wall_seconds": wall,
        }
    try:
        data = resp.json()
    except json.JSONDecodeError as exc:
        return {
            "_error": f"json_decode={exc}",
            "_body_head": resp.text[:200],
            "_wall_seconds": wall,
        }
    data["_wall_seconds"] = wall
    return data


def _extract_signals(response: dict[str, Any]) -> dict[str, Any]:
    out: dict[str, Any] = {}
    for k in _AGGREGATE_FIELDS:
        if k in response:
            out[k] = response[k]
    if "_wall_seconds" in response:
        out["_wall_seconds"] = response["_wall_seconds"]
    if "_error" in response:
        out["_error"] = response["_error"]
    return out


def _fmt(v: Any) -> str:
    if isinstance(v, float):
        return f"{v:.2f}"
    if isinstance(v, dict):
        if not v:
            return "{}"
        return json.dumps(v, separators=(", ", ":"))
    return str(v)


def _print_pair(idx: int, off: dict[str, Any], on: dict[str, Any]) -> None:
    print(f"\n=== Pair {idx} ===")
    keys = sorted(set(off.keys()) | set(on.keys()))
    col_w = max((len(k) for k in keys), default=12)
    print(f"  {'field':<{col_w}}  {'OFF':<32}  {'ON':<32}")
    for k in keys:
        a = _fmt(off.get(k, "—"))
        b = _fmt(on.get(k, "—"))
        marker = "  " if a == b else "Δ "
        print(f"{marker}{k:<{col_w}}  {a:<32}  {b:<32}")


def _summarise(
    toggle: str,
    pairs: list[tuple[dict[str, Any], dict[str, Any]]],
) -> None:
    print(f"\n=== Aggregate ({toggle}, n={len(pairs)} pairs) ===")
    if not pairs:
        print("  no pairs collected")
        return

    off_walls = [p[0].get("_wall_seconds", 0.0) for p in pairs]
    on_walls = [p[1].get("_wall_seconds", 0.0) for p in pairs]
    off_success = sum(1 for p in pairs if p[0].get("success"))
    on_success = sum(1 for p in pairs if p[1].get("success"))
    off_steps = [int(p[0].get("steps") or 0) for p in pairs]
    on_steps = [int(p[1].get("steps") or 0) for p in pairs]
    off_errors = [p[0]["_error"] for p in pairs if "_error" in p[0]]
    on_errors = [p[1]["_error"] for p in pairs if "_error" in p[1]]

    def _mean(xs: list[float]) -> float:
        return statistics.mean(xs) if xs else 0.0

    print(f"  success rate           OFF={off_success}/{len(pairs)}  ON={on_success}/{len(pairs)}")
    print(f"  wall mean              OFF={_mean(off_walls):.1f}s  ON={_mean(on_walls):.1f}s")
    print(f"  steps mean             OFF={_mean(off_steps):.1f}   ON={_mean(on_steps):.1f}")
    if off_errors or on_errors:
        print(f"  errors                 OFF={off_errors}  ON={on_errors}")

    # Sum aggregate dicts across pairs.
    for key in ("perceptual_summary", "loop_recoveries_by_reason",
                "done_rejections_by_reason", "speculation_summary"):
        off_agg: dict[str, Any] = {}
        on_agg: dict[str, Any] = {}
        for p in pairs:
            for tgt, src in ((off_agg, p[0].get(key, {})), (on_agg, p[1].get(key, {}))):
                if isinstance(src, dict):
                    for k, v in src.items():
                        if isinstance(v, (int, float)):
                            tgt[k] = tgt.get(k, 0) + v
        if off_agg or on_agg:
            print(f"  {key}")
            print(f"    OFF: {_fmt(off_agg)}")
            print(f"    ON:  {_fmt(on_agg)}")

    # Regression flags.
    print()
    flags: list[str] = []
    if on_success < off_success:
        flags.append(
            f"⚠️  success regression: ON dropped {off_success - on_success} successes vs OFF"
        )
    if any("_error" in p[1] for p in pairs):
        flags.append("⚠️  ON arm had request errors — investigate logs")
    if _mean(on_walls) > _mean(off_walls) * 1.5 and _mean(off_walls) > 5:
        flags.append(
            f"⚠️  wall-time regression: ON {_mean(on_walls):.1f}s vs OFF {_mean(off_walls):.1f}s"
        )
    if not flags:
        print("  ✅ no regression flags")
    else:
        for f in flags:
            print(f"  {f}")


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--toggle", required=True,
                   help="payload field name to ablate (e.g. perceptual_verify)")
    p.add_argument("--instruction", required=True)
    p.add_argument("--start-url", required=True)
    p.add_argument("--max-steps", type=int, default=6)
    p.add_argument("--settle-time", type=float, default=1.5)
    p.add_argument("--pairs", type=int, default=2,
                   help="number of ON/OFF pairs to run (default 2)")
    p.add_argument("--proxy-disabled", action="store_true", default=True)
    p.add_argument("--timeout", type=float, default=180.0)
    p.add_argument("--skip-warmup", action="store_true",
                   help="skip the warm-up request (only safe if a recent run already warmed the container)")
    args = p.parse_args(argv)

    endpoint = os.environ.get("MANTIS_ENDPOINT")
    token = os.environ.get("MANTIS_API_TOKEN")
    if not endpoint or not token:
        print("ERROR: set MANTIS_ENDPOINT and MANTIS_API_TOKEN", file=sys.stderr)
        return 2

    if not args.skip_warmup:
        print("Warm-up request (results discarded)…")
        _post_cua(
            endpoint, token,
            instruction="Look at the page and call done.",
            start_url=args.start_url,
            max_steps=2,
            settle_time=args.settle_time,
            proxy_disabled=args.proxy_disabled,
            toggle=None, toggle_value=None,
            timeout=args.timeout,
        )

    pairs: list[tuple[dict[str, Any], dict[str, Any]]] = []
    for i in range(1, args.pairs + 1):
        print(f"\n--- pair {i}: OFF arm ---")
        off = _post_cua(
            endpoint, token,
            instruction=args.instruction,
            start_url=args.start_url,
            max_steps=args.max_steps,
            settle_time=args.settle_time,
            proxy_disabled=args.proxy_disabled,
            toggle=args.toggle, toggle_value=False,
            timeout=args.timeout,
        )
        off_signals = _extract_signals(off)
        print(f"--- pair {i}: ON arm ---")
        on = _post_cua(
            endpoint, token,
            instruction=args.instruction,
            start_url=args.start_url,
            max_steps=args.max_steps,
            settle_time=args.settle_time,
            proxy_disabled=args.proxy_disabled,
            toggle=args.toggle, toggle_value=True,
            timeout=args.timeout,
        )
        on_signals = _extract_signals(on)
        pairs.append((off_signals, on_signals))
        _print_pair(i, off_signals, on_signals)

    _summarise(args.toggle, pairs)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
